---
- hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: Install GPG keys
    apt_key:
      url: "{{item}}"
      state: present
    with_items:
      - https://download.sublimetext.com/sublimehq-pub.gpg
      - https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
      - https://packages.microsoft.com/keys/microsoft.asc
      
  - name: Add specified repositories into sources list using specified filename
    apt_repository:
      repo: deb {{ item.repo }} {{ item.add }}
      state: present
      filename: "{{ item.file }}"
    with_items:
      - repo: https://download.sublimetext.com/
        add: apt/stable/
        file: sublime
      - repo: https://packages.microsoft.com/repos/vscode/
        add: stable main
        file: vscode
      - repo: https://repo.anaconda.com/pkgs/misc/debrepo/conda/
        add: stable main
        file: conda

  - name: Enable nvidia driver repo
    apt_repository:
      repo: ppa:nginx/stable

  - name: Install snaps 
    command: snap install {{item}} --classic
    with_items:
      - pycharm-community
      - webstorm

  - name: Install packages
    apt:
      state: installed
      pkg: 
        - code
        - conda
        - docker.io
        - hub
        - npm
        - python3-pip
        - sublime-text
        - vim
        - dkms 
        - build-essential
        - nvidia-driver-418

  - name: Enable docker on startup
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: Install typescript
    npm:
      name: typescript
      global: yes

  # This requires a new login shell to test
  - name: Source conda conda 
    file:
     src: "/opt/conda/etc/profile.d/conda.sh"
     dest: "/etc/profile.d/conda.sh"
     state: link
